// <auto-generated />
using System;
using DarwinLingua.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DarwinLingua.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DarwinLinguaDbContext))]
    [Migration("20260327230918_AddWordRelations")]
    partial class AddWordRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.ExampleSentence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GermanText")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimaryExample")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SentenceOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordSenseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WordSenseId")
                        .IsUnique()
                        .HasDatabaseName("IX_ExampleSentences_PrimaryPerSense")
                        .HasFilter("[IsPrimaryExample] = 1");

                    b.HasIndex("WordSenseId", "SentenceOrder")
                        .IsUnique();

                    b.ToTable("ExampleSentences", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.ExampleTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExampleSentenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationText")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExampleSentenceId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("ExampleTranslations", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.SenseTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslationText")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordSenseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WordSenseId")
                        .IsUnique()
                        .HasDatabaseName("IX_SenseTranslations_PrimaryPerSense")
                        .HasFilter("[IsPrimary] = 1");

                    b.HasIndex("WordSenseId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("SenseTranslations", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Topics", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.TopicLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("TopicLocalizations", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordCollocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Meaning")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WordEntryId", "SortOrder")
                        .IsUnique();

                    b.HasIndex("WordEntryId", "Text")
                        .IsUnique();

                    b.ToTable("WordCollocations", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Article")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentSourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfinitiveForm")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLemma")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PluralForm")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryCefrLevel")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("PronunciationIpa")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyllableBreak")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedLemma")
                        .HasDatabaseName("IX_WordEntries_Search_NormalizedLemma");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("PrimaryCefrLevel", "NormalizedLemma")
                        .HasDatabaseName("IX_WordEntries_Browse_Cefr_NormalizedLemma");

                    b.HasIndex("PublicationStatus", "NormalizedLemma")
                        .HasDatabaseName("IX_WordEntries_Search_ActiveNormalizedLemma");

                    b.HasIndex("NormalizedLemma", "PartOfSpeech", "PrimaryCefrLevel")
                        .IsUnique();

                    b.ToTable("WordEntries", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordFamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationLabel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WordEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WordEntryId", "SortOrder")
                        .IsUnique();

                    b.HasIndex("WordEntryId", "Lemma", "RelationLabel")
                        .IsUnique();

                    b.ToTable("WordFamilyMembers", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordGrammarNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WordEntryId", "SortOrder")
                        .IsUnique();

                    b.HasIndex("WordEntryId", "Text")
                        .IsUnique();

                    b.ToTable("WordGrammarNotes", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WordEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WordEntryId", "Kind", "Key")
                        .IsUnique();

                    b.HasIndex("WordEntryId", "Kind", "SortOrder")
                        .IsUnique();

                    b.ToTable("WordLabels", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Lemma")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WordEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WordEntryId", "Kind", "Lemma")
                        .IsUnique();

                    b.HasIndex("WordEntryId", "Kind", "SortOrder")
                        .IsUnique();

                    b.ToTable("WordRelations", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordSense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimarySense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SenseOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortDefinitionDe")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortGloss")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WordEntryId")
                        .IsUnique()
                        .HasDatabaseName("IX_WordSenses_PrimaryPerWordEntry")
                        .HasFilter("[IsPrimarySense] = 1");

                    b.HasIndex("WordEntryId", "SenseOrder")
                        .IsUnique();

                    b.ToTable("WordSenses", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimaryTopic")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordEntryId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("WordEntryId")
                        .IsUnique()
                        .HasDatabaseName("IX_WordTopics_PrimaryPerWordEntry")
                        .HasFilter("[IsPrimaryTopic] = 1");

                    b.HasIndex("WordEntryId", "TopicId")
                        .IsUnique();

                    b.ToTable("WordTopics", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.ContentOps.Domain.Entities.ContentPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("InputFileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("InsertedEntries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InvalidEntries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("SkippedDuplicateEntries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalEntries")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.ToTable("ContentPackages", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.ContentOps.Domain.Entities.ContentPackageEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CefrLevel")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentPackageId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ImportedWordEntryPublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedLemma")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartOfSpeech")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawLemma")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("WarningMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentPackageId");

                    b.ToTable("ContentPackageEntries", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Learning.Domain.Entities.UserFavoriteWord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordEntryPublicId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WordEntryPublicId")
                        .IsUnique();

                    b.ToTable("UserFavoriteWords", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Learning.Domain.Entities.UserLearningProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredMeaningLanguage1")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredMeaningLanguage2")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("UiLanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserLearningProfiles", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Learning.Domain.Entities.UserWordState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FirstViewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDifficult")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKnown")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastViewedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ViewCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WordEntryPublicId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "WordEntryPublicId")
                        .IsUnique();

                    b.ToTable("UserWordStates", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Localization.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupportsMeanings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsUserInterface")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Practice.Domain.Entities.PracticeAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueAtUtcAfterAttempt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueAtUtcBeforeAttempt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordEntryPublicId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AttemptedAtUtc")
                        .HasDatabaseName("IX_PracticeAttempts_User_AttemptedAtUtc");

                    b.HasIndex("UserId", "WordEntryPublicId", "AttemptedAtUtc")
                        .HasDatabaseName("IX_PracticeAttempts_User_Word_AttemptedAtUtc");

                    b.ToTable("PracticeAttempts", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Practice.Domain.Entities.PracticeReviewState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveSuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastAttemptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastOutcome")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSessionType")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessfulAttemptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalAttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WordEntryPublicId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DueAtUtc")
                        .HasDatabaseName("IX_PracticeReviewStates_User_DueAtUtc");

                    b.HasIndex("UserId", "WordEntryPublicId")
                        .IsUnique();

                    b.ToTable("PracticeReviewStates", (string)null);
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.ExampleSentence", b =>
                {
                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.WordSense", null)
                        .WithMany("Examples")
                        .HasForeignKey("WordSenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.ExampleTranslation", b =>
                {
                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.ExampleSentence", null)
                        .WithMany("Translations")
                        .HasForeignKey("ExampleSentenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.SenseTranslation", b =>
                {
                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.WordSense", null)
                        .WithMany("Translations")
                        .HasForeignKey("WordSenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.TopicLocalization", b =>
                {
                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.Topic", null)
                        .WithMany("Localizations")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordCollocation", b =>
                {
                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.WordEntry", null)
                        .WithMany("Collocations")
                        .HasForeignKey("WordEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordFamilyMember", b =>
                {
                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.WordEntry", null)
                        .WithMany("FamilyMembers")
                        .HasForeignKey("WordEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordGrammarNote", b =>
                {
                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.WordEntry", null)
                        .WithMany("GrammarNotes")
                        .HasForeignKey("WordEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordLabel", b =>
                {
                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.WordEntry", null)
                        .WithMany("Labels")
                        .HasForeignKey("WordEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordRelation", b =>
                {
                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.WordEntry", null)
                        .WithMany("Relations")
                        .HasForeignKey("WordEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordSense", b =>
                {
                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.WordEntry", null)
                        .WithMany("Senses")
                        .HasForeignKey("WordEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordTopic", b =>
                {
                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.Topic", null)
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DarwinLingua.Catalog.Domain.Entities.WordEntry", null)
                        .WithMany("Topics")
                        .HasForeignKey("WordEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.ContentOps.Domain.Entities.ContentPackageEntry", b =>
                {
                    b.HasOne("DarwinLingua.ContentOps.Domain.Entities.ContentPackage", null)
                        .WithMany("Entries")
                        .HasForeignKey("ContentPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.ExampleSentence", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.Topic", b =>
                {
                    b.Navigation("Localizations");
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordEntry", b =>
                {
                    b.Navigation("Collocations");

                    b.Navigation("FamilyMembers");

                    b.Navigation("GrammarNotes");

                    b.Navigation("Labels");

                    b.Navigation("Relations");

                    b.Navigation("Senses");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("DarwinLingua.Catalog.Domain.Entities.WordSense", b =>
                {
                    b.Navigation("Examples");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("DarwinLingua.ContentOps.Domain.Entities.ContentPackage", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
